"""v2 OpenAPI spec + Scalar docs.

The reference spec is generated by ts-rest from the full v2 contract (64 paths).
Here an equivalent spec is assembled with the same path set, info block and
server url so it renders in Scalar; byte-level equality with the ts-rest output
is out of scope (documented in the ledger).
"""

from ...compat import upstream_brand
from ...config import get_settings

_GET_PATHS = {
    "/bases/list",
    "/tables/get",
    "/tables/getComputeActivity",
    "/tables/getRecord",
    "/tables/getView",
    "/tables/getViewFilterLinkRecords",
    "/tables/getViewPluginInstall",
    "/tables/getViewSnapshots",
    "/tables/list",
    "/tables/listRecords",
    "/tables/listViewDocIds",
    "/tables/listViews",
}
_DELETE_PATHS = {
    "/tables/delete",
    "/tables/deleteByRange",
    "/tables/deleteField",
    "/tables/deleteRecords",
    "/tables/deleteView",
}
V2_PATHS = [
    "/bases/create",
    "/bases/duplicate",
    "/bases/list",
    "/tables/applyViewManualSort",
    "/tables/clear",
    "/tables/create",
    "/tables/createField",
    "/tables/createRecord",
    "/tables/createRecords",
    "/tables/createTables",
    "/tables/createView",
    "/tables/delete",
    "/tables/deleteByRange",
    "/tables/deleteField",
    "/tables/deleteRecords",
    "/tables/deleteView",
    "/tables/disableViewShare",
    "/tables/duplicateField",
    "/tables/duplicateRecord",
    "/tables/duplicateTable",
    "/tables/duplicateView",
    "/tables/enableViewShare",
    "/tables/explainCreateField",
    "/tables/explainCreateRecord",
    "/tables/explainDeleteField",
    "/tables/explainDeleteRecords",
    "/tables/explainDeleteTable",
    "/tables/explainUpdateField",
    "/tables/explainUpdateRecord",
    "/tables/get",
    "/tables/getComputeActivity",
    "/tables/getRecord",
    "/tables/getView",
    "/tables/getViewFilterLinkRecords",
    "/tables/getViewPluginInstall",
    "/tables/getViewSnapshots",
    "/tables/importCsv",
    "/tables/importRecords",
    "/tables/installViewPlugin",
    "/tables/list",
    "/tables/listRecords",
    "/tables/listViewDocIds",
    "/tables/listViews",
    "/tables/paste",
    "/tables/refreshViewShareId",
    "/tables/rename",
    "/tables/renameView",
    "/tables/reorderRecords",
    "/tables/restore",
    "/tables/submitRecord",
    "/tables/updateField",
    "/tables/updateProperties",
    "/tables/updateRecord",
    "/tables/updateRecords",
    "/tables/updateViewColumnMeta",
    "/tables/updateViewDescription",
    "/tables/updateViewFilter",
    "/tables/updateViewGroup",
    "/tables/updateViewLocked",
    "/tables/updateViewOptions",
    "/tables/updateViewOrder",
    "/tables/updateViewPluginStorage",
    "/tables/updateViewShareMeta",
    "/tables/updateViewSort",
]


def _method(path: str) -> str:
    if path in _GET_PATHS:
        return "get"
    if path in _DELETE_PATHS:
        return "delete"
    return "post"


def build_openapi_spec() -> dict:
    settings = get_settings()
    origin = settings.public_origin.rstrip("/")
    paths: dict = {}
    for path in V2_PATHS:
        method = _method(path)
        paths[path] = {
            method: {
                "summary": path,
                "tags": [path.split("/")[1]],
                "responses": {"200": {"description": "OK"}},
            }
        }
    return {
        "openapi": "3.1.1",
        "info": {"title": f"{upstream_brand().capitalize()} v2 API", "version": "0.0.0"},
        "servers": [{"url": f"{origin}/api/v2"}],
        "paths": paths,
        "components": {},
    }


def build_docs_html() -> str:
    return (
        "<!doctype html><html><head><title>API Reference</title>"
        '<meta charset="utf-8" />'
        '<meta name="viewport" content="width=device-width, initial-scale=1" />'
        "</head><body>"
        '<script id="api-reference" data-url="/api/v2/openapi.json"></script>'
        '<script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>'
        "</body></html>"
    )
