"""SQL construction layer for the per-base physical schema (postgres only).

Ports the DDL statements generated by the upstream postgres db-provider:
every base id maps to one schema holding its table data.
"""


def _quoted_identifier(name: str) -> str:
    if not name or "\x00" in name:
        raise ValueError("Invalid schema name")
    return '"' + name.replace('"', '""') + '"'


def create_schema_sql(schema_name: str) -> list[str]:
    """`create schema if not exists` + revoke public access."""
    quoted = _quoted_identifier(schema_name)
    return [
        f"CREATE SCHEMA IF NOT EXISTS {quoted}",
        f"REVOKE ALL ON SCHEMA {quoted} FROM PUBLIC",
    ]


def drop_schema_sql(schema_name: str) -> str:
    """`DROP SCHEMA IF EXISTS ... CASCADE`, used on permanent base deletion."""
    return f"DROP SCHEMA IF EXISTS {_quoted_identifier(schema_name)} CASCADE"
